# @package task

defaults:
  - detection/_default

# This file allows you to use task=detection directly
# The actual task name will be provided via command line override
# or by creating specific task files in the wildfin/ directory
