_target_: dojo.config_dataclasses.benchmark.BenchmarkConfig

name: sciduc
tasks:
    - example-sciduc-task
    - wildfin

# Overrides for all tasks
overrides: {}

# Task-specific overrides
task_overrides: {}
