_target_: dojo.config_dataclasses.benchmark.BenchmarkConfig

name: sciduc
tasks:
    - example-sciduc-task
    - wildfin
    - bucktales
    - cell-seg
    - chimpact
    - inat
    - cub
    - cub_ssl
    - cub_sett1

# Overrides for all tasks
overrides: {}

# Task-specific overrides
task_overrides: {}
