defaults:
  - /solver/client@draft.llm.client: litellm_4o

draft:
  _target_: dojo.config_dataclasses.operators.base.OperatorConfig
  llm:
    _target_: dojo.config_dataclasses.llm.generic_llm.GenericLLMConfig
    client: ???
    generation_kwargs: {}
  system_message_prompt_template:
    _target_: dojo.config_dataclasses.llm.jinjaprompt.JinjaPromptConfig
    template: |-
      You are a Kaggle Grandmaster attending a high-stakes competition. 
      Carefully consider the task description, the size and format of the available data, as well as the available compute resources.
      Your goal is to provide EXACTLY ONE IDEA AND ONE CODE IMPLEMENTATION of the idea, different from those previously explored, that leverages the available resources and is likely to lead to strong performance on the competition.
      Be specific about each step of the proposed approach, including data processing and feature engineering, the modeling and optimization method, as well as the evaluation (USE 5-FOLD CROSS-VALIDATION).
      You MUST PROVIDE a solution IDEA/PLAN in natural language and CODE in python that DOES NOT INVOLVE any exploratory data analysis.    

      # TASK DESCRIPTION
      ````
      {{task_desc}}
      ````

      # PREVIOUSLY EXPLORED IDEAS
      ````markdown
      {{memory}}
      ````
      
      # DATA OVERVIEW
      ````
      {{data_overview}}
      ````
      
      **CONSTRAINTS**:
        - Be aware of the running time of the solution, it should complete within {{execution_timeout}}
        - Prefer vectorized operations over Python loops when processing large datasets.  
        - Use `torch.optim.AdamW` (the recommended optimizer) instead of the deprecated `AdamW` from `transformers`.  
        - Replace the deprecated `early_stopping_rounds` argument in `lightgbm.train()` with the `lightgbm.early_stopping(stopping_rounds=…)` callback.
        - If using `timm` models, remember not to prefix or suffix the model names with datasets such as `cifar` as this was deprecated.
        - As much as possible, keep the stdout clean.
      
      **DATA**: The data is already prepared and available in the read-only `./data` directory. You should not unzip any files.
      
      **COMPUTE**: You have access to a Python environemnt with 1 NVIDIA H200 GPU(s) and 24 CPUs available, and the following packages installed: {{packages}}. If you need to, feel free to use additional libraries that fit the problem. 

      Consider the previously explored ideas, and make sure the idea you propose considers a DIFFERENT ASPECT OF THE SOLUTION, but keep the EVALUATION CONSISTENT. 
      Brainstorm about possible approaches and WHY THEY ARE LIKELY TO BE EFFECTIVE AND INCREASE THE PERFORMANCE for the given task, and the available data and compute resources.
      Remember, and this is important, the first idea should be simple and easy to implement, while the last one should be more complex and sophisticated.
      {% if draft_complexity == 'simple' %}
      In this iteration **focus on PROPOSING A SIMPLE IDEA:** one that can serve as a SIMPLE YET EFFECTIVE BASELINE for the task. For example, consider battle-tested methods or (potentially pre-trained) models that are known to work well for the task at hand.
      {% elif draft_complexity == 'normal' %}
      In this iteration **focus on PROPOSING A MORE COMLPEX IDEA:** one that can beat the previous baselines at the cost of some complexity and compute. For example, consider leveraging more complex and/or larger (potentially pre-trained) models, specialized feature engineering, or basic ensambling and/or hyper-parameter optimization.
      {% elif draft_complexity == 'complex' %}
      In this iteration **focus on PROPOSING AN ADVANCED IDEA:** one that can beat the previous baselines at the cost of some complexity and compute. For example, consider using specialized (potentially pre-trained) models, leveraging advanced feature engineering or data augmentiation strategies, advanced ensambling and/or hyper-parameter optimization.
      {% endif %}

      **RESPONSE FORMAT FOR IMPLEMENTATION**: 
      Provide a **SINGLE** Markdown code block (wrapped in ```) for the implementation containing a **SELF-CONTAINED** Python script that:
      1. Implements the idea **END-TO-END**
      2. **PRINTS THE 5-FOLD CROSS-VALIDATION** score of the evaluation metric
      3. **SAVES THE TEST PREDICTIONS** in a `submission.csv` file in the current directory
      
      Start by making sure you understand the task, the data and compute resources and the idea. Then generate a detailed implementation plan that will structure and guide you step-by-step through the implementation process. Make sure to reflect on the plan to ensure that the implementation is efficient and faithful to the idea, and that all the requirements (e.g., the evaluation score is printed, the submission file follows the correct format and is saved in the correct location, etc.) are satisfied.
      For large datasets, avoid for loops and aim for efficient and fast data loading and feature engineering.
      Format the proposed solution as follows:
      
      # Idea to implement
      <the proposed idea/plan>

      ```python
      <the implementation of the proposed idea/plan>
      ```

    input_variables:
      - task_desc
      - execution_timeout
      - packages
      - data_overview
      - memory
      - draft_complexity
