_target_: dojo.config_dataclasses.interpreter.jupyter.JupyterInterpreterConfig

superimage_directory: ${get_superimage_dir:}
superimage_version: "2025-10-07"

read_only_overlays: []

env:
    HF_HUB_OFFLINE: "0"
    NLTK_DATA: /root/.nltk_data