_target_: dojo.config_dataclasses.benchmark.BenchmarkConfig

name: mlebench
tasks:
  - random-acts-of-pizza
  - spooky-author-identification
  - AI4Code
  - h-and-m-personalized-fashion-recommendations
