_target_: dojo.config_dataclasses.client.base.ClientConfig
api: litellm
model_id: "deepseek-ai/DeepSeek-R1"
base_url: "http://<<<SELF_HOSTED_ENDPOINT>>>/v1"
use_azure_client: False
provider: selfhosted

