_target_: dojo.config_dataclasses.benchmark.BenchmarkConfig

name: wildfin
tasks:
    - example-task
    # Add more Wildfin task names here as they become available

# Overrides for all tasks
overrides: {}

# Task-specific overrides
task_overrides: {}
