
# @package task

_target_: dojo.config_dataclasses.task.sciduc.SciDucConfig
name: ???
benchmark: sciduc

# ~~~ Task data ~~~
cache_dir: ${get_sciduc_data_dir:}

# ~~~ Workspace preparation ~~~
task_dir: ${task.cache_dir}/${task.name}

# ~~~ Evaluation and results ~~~
submission_fname: submission.json