# @package task

_target_: dojo.config_dataclasses.task.sciduc.SciDUCTaskConfig
name: ???
benchmark: sciduc

# ~~~ Task data ~~~
cache_dir: ${get_sciduc_data_dir:}

# ~~~ Workspace preparation ~~~
public_dir: ${task.cache_dir}/${task.name}/prepared/public
private_dir: ${task.cache_dir}/${task.name}/prepared/private

# ~~~ Evaluation and results ~~~
submission_fname: submission.csv